# Generated by Django 2.2.9 on 2020-07-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200714_1948'),
        ('accounts', '0031_auto_20200714_1737'),
    ]

    operations = [
    ]
