# Generated by Django 2.2.9 on 2020-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_merge_20200715_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='region',
            field=models.CharField(default='uncategorized', max_length=200, null=True),
        ),
    ]
